name: build
on:
  push:
    paths:
      - '**.js'
jobs:
  build:
    name: my job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]
        node: [10, 12, 14]
        include:
          - node: 13
            os: ubuntu-18.04
            experimental: true
        exclude:
          - os: ubuntu-latest
            node: 10
    steps:
      - uses: actions/checkout@v2
      - name: Use node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run build --if-present
      - name: test step
        env:
          MY_VAR: Hi there!
          FIRST_NAME: John
        run: |
          echo "$MY_VAR $FIRST_NAME"
      - name: next step
        if: success()
        run: echo "The previous step has finished successfully"
      - name: First interaction
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Msg that will be displayed on users first issue'
          pr-message: 'Message that will be displayed on first pr'

